project:
  type: website
  output-dir: _site

  preview:
    port: 4400
    browser: false
  render:
    - "*.qmd"
    - "!deliverables-solutions/"

editor:  
  render-on-save: true
  preview: true

execute:
  freeze: false
  fig-align: center

website:
  title: "AD 698 Applied Generative AI Business Analytics"
  # comments: 
  #   utterances:
  #       repo: BostonAnalytics/AD698-generative-ai-for-BA
  #       label: utterance # optional
  #       theme: icy-dark # optional
  #       issue-term: pathname # optional
  navbar: false
  # --- Uncomment below if navigation is needed ---
    # search: true
    # left:
    #   - text: Syllabus
    #     href: index.qmd
    #   - text: Schedule
    #     href: schedule.qmd
    #   - text: Deliverables
    #     href: deliverables.qmd
    #   - text: "Module 01"
    #     menu:
    #       - text: "Module Highlights"
    #         href: M01/M01_Highlights.qmd
    #       - text: "Lecture Notes 1.1"
    #         href: M01/M01_LN01.qmd
    #       - text: "Presentation 1.1"
    #         href: M01/M01_P01.qmd
    #       - text: "Lecture Notes 1.2"
    #         href: M01/M01_LN02.qmd
    #       - text: "Presentation 1.2"
    #         href: M01/M01_P02.qmd
    #       - text: "Lab 1.1"
    #         href: M01/M01_Lab01.qmd
    #       - text: "Lab 1.2"
    #         href: M01/M01_Lab02.qmd
    #       - text: "Module 1 Assignment"
    #         href: M01/M01_A.qmd
    #       - text: "Module 1 Project"
    #         href: M01/M01_Proj.qmd 
    #       - text: "Module Wrap-Up"
    #         href: M01/M01_Wrapup.qmd
    #   - text: "Module 02"
    #     menu:
    #       - text: "Module Highlights"
    #         href: M02/M02_Highlights.qmd
    #       - text: "Lecture Notes 2.1"
    #         href: M02/M02_LN01.qmd
    #       - text: "Presentation 2.1"
    #         href: M02/M02_P01.qmd
    #       - text: "Lecture Notes 2.2"
    #         href: M02/M02_LN02.qmd
    #       - text: "Presentation 2.2"
    #         href: M02/M02_P02.qmd
    #       - text: "Lab 2.1"
    #         href: M02/M02_Lab01.qmd
    #       - text: "Lab 2.2" 
    #         href: M02/M02_Lab02.qmd
    #       - text: "Module 2 Assignment" 
    #         href: M02/M02_A.qmd
    #       - text: "Module 2 Project"  
    #         href: M02/M02_Proj.qmd
    #       - text: "Module Wrap-Up"
    #         href: M02/M02_Wrapup.qmd

format:
  html:
    theme: [cosmo, ./theme/metanalytics.scss]
    toc: true
    number-sections: true
    highlight-style: github
    code-overflow: wrap
    html-math-method: katex
    # comments:
    #   utterances:
    #     repo: BostonAnalytics/AD698-generative-ai-for-BA

crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  title-delim: "**.**"


resources:
  - theme/03_geometric.svg