project:
  type: website
  preview:
    port: 4300
    browser: false
  render:
    - "*.qmd"
    - "!delivarables-solutions/labs/*_sol.ipynb"
    - "!delivarables-solutions/labs/*_sol.qmd"
    - "!delivarables-solutions/assignments/*_sol.ipynb"
    - "!delivarables-solutions/assignments/*_sol.qmd"
    - "!classroom-organization/"
    - "!powerpoint/"
    - "!Fall2024/"
    - "!data/"
    - "Announcements/"
    - "delivarables-solutions/"

editor:  
  render-on-save: true
  preview: true

execute:
  freeze: false
  keep-ipynb: false
  fig-align: center

website:
  title: "AD 688 Web Analytics"
  navbar: false
    # search: true
    # left:
    #   - text: Syllabus
    #     href: index.qmd
    #   - text: Schedule
    #     href: schedule.qmd
    #   - text: Deliverables
    #     href: deliverables.qmd
    #   - text: "Module 0"
    #     menu:
    #       - text: "Lecture Notes 0.1"
    #         href: M0/M0_lecturenotes0.1.qmd
    #       - text: "Presentation 0.1"
    #         href: M0/M0_presentation0.1.qmd
    #       - text: "Lecture Notes 0.2"
    #         href: M0/M0_lecturenotes0.2.qmd
    #       - text: "Presentation 0.2"
    #         href: M0/M0_presentation0.2.qmd
    #       - text: "Lecture Notes 0.3"
    #         href: M0/M0_lecturenotes0.3.qmd
    #       - text: "Presentation 0.3"
    #         href: M0/M0_presentation0.3.qmd
    #   - text: "Module 1"
    #     menu:
    #       - text: "Lecture Notes 1.1"
    #         href: M1/M01_lecturenotes01.qmd
    #       - text: "Presentation 1.1"
    #         href: M1/M01_presentation01.qmd
    #       - text: "Lab 01"
    #         href: M1/M01_lab01.qmd
    #       - text: "Lecture Notes 1.2"
    #         href: M1/M01_lecturenotes02.qmd
    #       - text: "Presentation 1.2"
    #         href: M1/M01_presentation02.qmd
    #       - text: "Lab 02"
    #         href: M1/M01_lab02.qmd
    #       - text: "Assignment 01"
    #         href: M1/M01_assignment01.qmd
    #       - text: "Project 01"
    #         href: M1/M01_project01.qmd
    #   - text: "Module 2"
    #     menu:
    #       - text: "Lecture Notes 2.1"
    #         href: M2/M02_lecturenotes01.qmd
    #       - text: "Presentation 2.1"
    #         href: M2/M02_presentation01.qmd
    #       - text: "Lab 03"
    #         href: M2/M02_lab01.qmd
    #       - text: "Lecture Notes 2.2"
    #         href: M2/M02_lecturenotes02.qmd
    #       - text: "Presentation 2.2"
    #         href: M2/M02_presentation02.qmd
    #       - text: "Lab 04"
    #         href: M2/M02_lab02.qmd
      
format:
  html:
    bibliography: references.bib
    theme: [cosmo, ./theme/site.scss]
    toc: true
    number-sections: true
    embed-resources: true
    highlight-style: github
    code-overflow: wrap
    html-math-method: mathml
    grid:
      sidebar-width: 100px
      body-width: 1100px
      margin-width: 400px
      gutter-width: 1.5rem

crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  title-delim: "**.**"